[build]
  command = "npx prisma generate && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NEXT_PUBLIC_SITE_URL = "https://kathamrut.netlify.app"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

[images]
  remote_images = ["https://ep-hidden-dew-aqn81atd.c-8.us-east-1.aws.neon.tech/**", "https://*.netlify.app/**"]