[build]
  command = "npx prisma generate && npx prisma migrate deploy && npm run build"
  publish = ".next/standalone"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "bun"